language: go

sudo: false

go:
  - 1.5.3
  - 1.6.1

before_install:
    - mkdir -p $GOPATH/bin
    - curl -L https://github.com/docker/machine/releases/download/v0.7.0/docker-machine-`uname -s`-`uname -m` > $GOPATH/bin/docker-machine && chmod +x $GOPATH/bin/docker-machine
    - go get github.com/Azure/go-ansiterm/winterm || true
    - go get github.com/docker/go-units || true
    - go get -u -f github.com/scaleway/docker-machine-driver-scaleway

script:
    docker-machine create -d scaleway -h | grep "scaleway"
